// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrgdgwsvzktjsofuraef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZ2Rnd3N2emt0anNvZnVyYWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjE4MzMsImV4cCI6MjA1ODAzNzgzM30.TVSPtBDXgbRMQg2PiN0abZa6J5XjFHLJ-xz0ubQiF8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);